# Generated by Django 5.0.4 on 2024-10-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRestau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
